Tb = int(input('Digite um Numéro: '))
print('_' * 15)
print('{} x {:2} = {}'.format(Tb, 1, Tb * 1))
print('{} x {:2} = {}'.format(Tb, 2, Tb * 2))
print('{} x {:2} = {}'.format(Tb, 3, Tb * 3))
print('{} x {:2} = {}'.format(Tb, 4, Tb * 4))
print('{} x {:2} = {}'.format(Tb, 5, Tb * 5))
print('{} x {:2} = {}'.format(Tb, 6, Tb * 6))
print('{} x {:2} = {}'.format(Tb, 7, Tb * 7))
print('{} x {:2} = {}'.format(Tb, 8, Tb * 8))
print('{} x {:2} = {}'.format(Tb, 9, Tb * 9))
print('{} x {:2} = {}'.format(Tb, 10, Tb * 10))
print('_' * 15)
